modLoader = "javafml"
loaderVersion = "[1,)"
license = "0bsd"
issueTrackerURL = "https://github.com/null2264/LibreExpFix/issues"

[[mods]]
modId = "libreexpfix"
version = "${version}"
displayName = "LibreExpFix"
displayURL = "https://github.com/null2264/LibreExpFix"
logoFile = "icon.png"
authors = "null2264"
description = "Fix experience bug after teleporting across dimension"

[[mixins]]
config = "libreexpfix.mixins.json"

[[dependencies.libreexpfix]]
modId = "neoforge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libreexpfix]]
modId = "minecraft"
mandatory = true
versionRange = "${mcversion}"
ordering = "NONE"
side = "BOTH"
